import os
from building import *

cwd = GetCurrentDir()

# add general drivers
src = Glob('*.c')
src += Glob('port/*.c')

# add cubemx drivers
src += Glob('CubeMX_Config/Core/Src/*.c')
src += Glob('board.c')

path = [cwd]
path += [cwd + '/port']
path += [cwd + '/CubeMX_Config/Core/Inc']

group = DefineGroup('board', src, depend = [''], CPPPATH = path)

Return('group')
