from building import *
import os

cwd = GetCurrentDir()
group = []

for child in ('Board', 'Drivers', 'Storage'):
    script = os.path.join(cwd, child, 'SConscript')
    if os.path.isfile(script):
        group += SConscript(script)

Return('group')
